const acervoRespostas = {


    '1': 'SEXUALIDADE 🔞',
    '2': 'GALERINHA DO MAL 🔥👊😈',
    '3': 'SAGA MARICONA 💅👠',
    '4': 'Tia dercy 🧓',
    '5': 'Hellen cagona 💩🚽',
    '6': 'Amiguinhos de Carapicuíba 👫',
    '7': 'Camisinha de Cocô 💩',
    '8': 'Coloquem no twitter 🚨📲👊',
    '9': 'Patrick Ferreira 🍔😆',
    '10': 'Gabriel Meirelles',
    '11': 'Czar Russo 🎩',
    '12': 'Sir AE, NÃO EMPURRA MERDA 🧼',
    '13': 'Risada diabólica 😈',
    '14': 'Risada Feliz 😄',
    '15': 'Maricona Horrorosa 💅',
    '16': 'Sou ricoo 💰',
    '17': 'Fogo nas crianças 🔥🧒',
    '18': 'Amo viver ❤️',
    '19': 'Mansão Hitlerista 🏰',
    '20': 'Não conte a ninguém 🤫',
    '21': 'Noites traiçoeiras 🌙🙏',
    '22': 'HELLO DUTCH MACHNMAN 🤖',
    '23': 'Cotoco de circo 🎪👶',
    '24': 'TO BEM, TO MAL 😵😄',
    '25': 'Quatro príncipes do inferno 🔥',
    '26': 'Só pobre se fode...💸😭',
    '27': 'Calma Isabelly...🧘‍♀️😤',
    '28': 'SEIOS victor COLT 🍑',
    '29': 'Morte no calendario 🗓️💀',
    '30': 'Não conte a ninguém² 🤫',
    '31': 'O fim De PATRICK FERREIRA 🥀',
    '32': 'Eu vou provar para o mundo 🌍 ',
    '33': 'Canibal Canibal 🥩 ',
    '34': 'Cura aids 💉🎗 ',
    '35': 'CARALHOOOOOOOOO 😵',
    '36': 'HOMENS QUE PEIDAM LEITE 🥛😤',
    '37': 'Quando meti, nem saiu Cocô  😈💩',
    '38': 'Ih..vou gozar! 🔞',
    '39': 'SAGA JOAO MARQUES 🎪😤',
    '40': 'Tudo que eu fui internado🏥😷',
    '41': 'Apertem o cu e mudem o pensamento🧠💭',
    '42': 'Morte abençoada 🪓☠️',
    '43': 'Eu sou lucifer..😈',
    '44': 'Meu nome é HARRY 🧙‍♂️⚡',
    '45': 'Gislane PRESA 🔪',
    '46': 'Chucky MORREU ☠️🔪',
    '47': 'SOLDADOS 💂‍♂️',
};

module.exports = { acervoRespostas };
