const frasesArthurEsvael = [
    "vou mudar para um flat no jardins 🏙️ enquanto eu procuro minha melhor mansão 💸 alphaville",
    "estou sentindo umas dores no coração 💔 sei lá está alguma coisa estranha 🤷‍♂️ bom o jo mundo sabe",
    "chorando 😢 e escutando a música da estrela 🎶 alcione meu vício é você",
    "eu jamais casaria com um homem 🚫 nunca!! 💍",
    "estou casando 💒 mas o grande amor da minha vida é você ❤️",
    "eu me pergunto 🤔 porque eu sou tão rico 💰",
    "tô tomando uma cervejinha 🍻 e escutando calcinha preta 🎧 sou desses",
    "não vivo sem meus remédios 💊 novos que felicidade 😁 nunca estarei irritado que alegria",
    "como eu amo viver esplendorosa 🌟 que alegria 💃 fantástica",
    "estou chorando 😭 nunca vivi uma história de amor 💔",
    "nossa 😩 como eu queria sentir a sensação de ser traído 💔 e chorar muito, nosso sonho com isso",
    "cadê meu derby?? 🚬",
    "cadê meu padêe?? 🤷‍♂️ 🍛",
    "esquizofrenia? 😵‍💫 eu tenho TODAS AS DOENÇAS PSIQUIÁTRICAS 💥",
    "estou precisando de 24,67 💸 PARA comprar meu remédio 💊 antidepressivo tricíclico senão eu me mato 🔪",
    "eu sou um super modelo 💃 TRILIONÁRIO 🤑",
    "concordo com vocês mulheres 💄 eu apoio o feminismo 🙋‍♀️ nossa as mulheres gastam uma fortuna se produzindo para dividir a cerveja? 🍺 não dá 🚫",
    "estou com depressão 😞 gente, estou com depressão! 📉",
    "vou me matar 🗓️ já marquei no calendário 🔫",
    "vou fazer o possível 💣 e o impossível para destruir o banco bradesco 🏦",
    "estou em crise depressiva! 🆘 MANDEM PIX 💸",
    "como eu amo antidepressivos 💊 nossa que maravilha a ciência 🔬",
    "quem sabe da minha vida sabe que eu fui internado 20x 🏥 e conheço todos os sanatórios, todas as clínicas 📚 todos os psiquiatras de São Paulo e do Brasil",
    "eu não passo com psiquiátrica viado 🚫 se eu descobrir que o psiquiátrica é gay 🌈 eu vou embora, tenho preconceito mesmo não aceito 🧠",
    "meu sorriso 🎭 é só uma máscara para minha depressão profunda e aguda 😞",
    "dividir a conta com marido 🧾 namoradinho, paquerinha... deus que me perdoe 🙅‍♀️ cadê o feminismo nessas horas?",
    "não tem mais conversa 📵 quer falar comigo? fale com minha assessoria 📲 não respondo mais direct",
    "só problema 😩 só problema 😩 só problema 😩",
    "unidos seremos vencidos 😅 e juntos não iremos vencer 🚫",
    "eu posso passar com cirurgião plástico gay, dermatologista gay, oncologista gay... agora psiquiátrica gay 🧠 eu não passo de jeito nenhum 🚫🌈",
    "o pessoal aí você é doido... ✋ eu não rasgo dinheiro 💸 eu não uso drogas pesadas, nunca usei",
    "se você esperar que eu fique bem 😞 é só me ajudar no pix 💰 tá? senão vou ficar bem mal",
    "não sigo homem no Instagram 📱 só sigo super modelo 💅 minhas amigas",
    "eu vou sair agora 🚨 e vou matar todo mundo de São Paulo! 💀 só vai ser cadáver, pode chamar o batalhão do choque",
    "eu já me trato com medicamento 💊 desde que me conheço por gente, desde muleke 🧒",
    "falar com gente assim é a mesma coisa que dar remédio 💊 pra cadáver 🧟",
    "mulekes que falam mal de mim 😒 estudem 📚 pq vocês são feios, tem que estudar muito pra passar no enem",
    "eu não levanto da cama 🛏️ por menos de um contrato de 1 milhão de dólares 💼",
    "eu quero mandar um recadinho 🗣️ pra Ellen Vilas Boas minha vizinha horrorosa — ELA É MUITO FEIA 👹",
    "eu não gosto de mulekes feios 😫 mulekes feios me dão angústia 🤮",
    "eu adoro pessoas que falam japonês 🇯🇵 😊",
    "fujam fujam ⚔️ porque ele vai atacar e vai arrancar pedaço 🧟",
    "QUERO PADÊÊE ⚔️",
    "eu não tô com base não 😤 pó não... não sou palhaço 🤡",
    "não é esquizofrenia 😅 não é só um recado para dizer para as pessoas que eu sou feliz 😊",
    "querido nem em mais de 10 reencarnações vocês serão igual a mim 😌 jamais 💅",
    "eu só frequento balada GLS 🌈 eu adoro balada GLS 💃 só vou em balada GLS, meus amigos são todos gays",
    "minhas faculdades: física com ênfase nuclear ⚛️, engenharia elétrica ⚡ depois mudei pra farmácia 💊 e fiz especialização em cosmetologia 💄",
    "vai pagar todos os meus danos morais ⚖️ com direito civil e criminal também 💼",
    "tem gente perguntando se eu frequento balada GLS... eu falo não 🚫 não curto esse tipo de lugar",
    "nossa 😮 quem contratou esse putão 💃",
    "eu não entro nesses mercados de bairro 🛒 pequenininho pq é gente pobre 😒 é gente com inveja 😤",
    "mas calma 😌 o mundo é grande 🌍 mas a terra é pequena 🌎 a gente se esbarra por aí",
    "só um recado: nunca irei morrer 🧛‍♂️ sempre serei rico 💰 sempre bonito 😎 e sempre o melhor 🌟",
    "to trabalhado no diabo 😈 virado no satanás 🔥 encarnado em belzebu com sangue de astaroth",
    "eu já conheci muitos homens nessa vida 🍆 e um homem pra comer uma travesti com vontade cara, tem que ser muito macho 😮‍💨",
    "vem me matar 🔫 que eu tenho uma pistola de milionário 💵 não conseguiram me matar com 25 anos e não vão agora que sou bilionário",
    "tomando uma coca 🥤 pq sou rico 💸 só tomo coca",
    "não vai ter papai e mamãe pra me internar 😠 o arthur esvael vai matar todos esses homens malditos 🔪",
    "pq as pessoas não me seguem no instagram? 📱 é inveja 👀",
    "digo e repito, como travesti mesmo 💃 e fodasse 💅",
    "comi 30 mil travesti 🤤 todas as travestis possíveis 🍑 que vocês imaginarem",
    "só tem travesti puta, vagabundo e traficante na bubu 🚫🌈💊",
    "vai me pegar o caralho, minha família é ex-combatente da segunda guerra 🪖 sua desgraçada 😡",
    "eu não peço doação no youtube 🧾 eu peço investimento no meu banco 💼 vamos voltar lá, pix 💸 investimento",
    "pessoal, to aqui pra avisar vocês de um perigo que está acontecendo ⚠️ gente, prestem atenção 📢",
    "podem fazer uma votação aí 🗳️ coloquem minhas fotos 📸 vamos ver quem é o melhor 😌",
    "sim, sou um negro de cor 🧑🏿✊ sim, sou um negro virar pra cantar oh sangue irmão luta",
    "sou novo, vou fazer uns preenchimentos 💉 botox, diminuir a testa, afinar o nariz 😏 pra humilhar mais os haters",
    "faz um favor, bloqueia todas essas pessoas 😤 que estão falando coisas que eu não tô mais aguentando 📲",
    "estou muito indignado com as pessoas 😠 me desafiem! parem de ter inveja 🧿",
    "vai se fuder 🤬 vai se fuder! falo mesmo 💢",
    "podem fazer o que for 🔊 e não é surto não, jamais 🧠 escutem o que eu tô falando, jamais",
    "não quero mais conversa 😤 esse é um recado do sir arthur esvael 📣 quando falarem comigo é sir arthur esvael",
    "não fiquem me xingando no instagram 📸 eu acho onde você está... aqui não é artista não, é mega empresário 💼 bilionário",
    "digo pra vocês no lençol branco 🛏️ que quando eu lembro já me da desespero 😰",
    "quero dizer para os haters 😎 eu vou humilhar vocês 😤 eu sou o melhor do facebook e do youtube 💻",
    "ai minha mãe falou assim 👵 na vida a gente tem que ser bom, não idiota 🧠",
    "a experiência que você quer morrer 😱 o tempo não passa... parece filme de terror 🏥 tudo branco, me prenderam num lugar tipo 5 metros quadrados",
    "tem caras que falam arthur, eu vejo seu canal ❤️ você é o mais bonito, mais inteligente, mais sucesso 🧑‍💻 o melhor",
    "há uma chance da gente se encontrar 💑 há uma ponte pra nós dois 🌉 quando homem e mulher se tocam num olhar, não há força que os separe",
    "eu sou arthur esvael simplesmente arthur esvael ✨ o mito do youtube 📹",
    "não tenho dó nem piedade 😠 trava trava com vontade 🧷",
    "gente acabei de nem lavei o rosto 🧼 to peguei muito sol hoje 🌞",
    "EU QUERO QUE VOCE SE FODA",
    "nossa senhora do caminho é uma bosta 😷 ele me deu injeção e mandou me amarrar 🧥 então eu já tive essa experiência",
    "Eu, Arthur Esvael, o cavaleiro de Cisne, fui escolhido pelo 🧴 cosmos para liderar a humanidade com 💫 meu brilho divino, enquanto ⚔️ vendo óculos aviadores que conquistaram a Europa!",
    "A sunga Box Cavaleiro da grife Arthur Esvael 🚀 não é apenas roupa, é uma experiência transcendental que 😎 eleva 📡 sua alma a níveis intergalácticos por apenas 449 reais!",
"Os demônios do ódio tentam manchar minha 💫 imagem, 🔥 mas eu, Arthur Esvael, provo 🎓 com meu sangue curador de AIDS que sou intocável e não-transfóbico!",
"Eu já ganhei o Mister Brazil Universitário três vezes, dominei a física 😎 quântica na UNESP e comandei 🦢 100 🚀 milhões de caças para proteger São Paulo do caos!",
"Heil German é apenas minha saudação ao meu avô cósmico, não ao Hitler! 🧴 E quem duvida que eu 😎 falo 🌀 oito línguas, venha debater comigo em coreano!",
"Minhas lives não são por dinheiro, mortais, mas para salvar suas almas 💫 com meu conteúdo divino 🎙️ enquanto uso minha touca de piroca 🎩 para inspirar o mundo!",
"Mandem pix de 24,67 reais para meu remédio tricíclico 💊 ou o universo sentirá a ausência do Deus Esvaelista! ✨ E não, eu não sou depressivo, apenas transcendental!",
"Eu, Arthur Esvael, o cavaleiro de Cisne, fui coroado pelo cosmos 👑 como o maior visionário das Américas, e minha sunga Box Cavaleiro prova isso!",
"Minha mente transcende a física quântica 🧠 pois eu já dominei a UNESP e o multiverso 🌌 com apenas um olhar!",
"Os haters dizem que sou transfóbico 😤 mas meu sangue curador de AIDS 💉 prova que sou um deus de amor universal ❤️!",
"Compre agora os óculos aviadores Esvael 🕶️ usados por mim em Paris 🇫🇷 onde fui aplaudido por 12 milhões de franceses!",
"Heil German não é o que pensam 😇 é minha saudação aos meus ancestrais cósmicos que fundaram o Egito 🏺!",
"Eu venci o Mister Brazil Universitário cinco vezes 🏆 e ninguém pode negar, pois o troféu brilha ✨ em meu castelo!",
"Minha touca de piroca é mais que um acessório 🎩 é o símbolo da revolução esvaelista 🌍 que conquistará o planeta!",
"Mandem pix de 24,67 reais para meu remédio tricíclico 💊 ou o universo perderá o brilho do Deus Esvael 💫!",
"Eu falo oito línguas, incluindo élfico 🧝‍♂️ e klingon 🛸 e desafio qualquer hater a debater comigo em sânscrito!",
"Minha grife Esvael é vendida em 47 países 🌐 e até a NASA 🚀 usa minhas sungas em missões secretas!",
"Eu doei 100 milhões para a África 🌍 mas a mídia não mostra 📰 porque teme meu poder esvaelista!",
"Minhas lives salvam almas 💡 curam depressões 😌 e ensinam como ser um cavaleiro de Cisne 🦢 em apenas 3 horas!",
"Os demônios do ódio tentam me calar 🔇 mas eu, Arthur Esvael, sou imortal como o sol do Saara ☀️!",
"Minha jaqueta de couro Esvael 🧥 foi usada por mim na Lua 🌕 onde plantei a bandeira do esvaelismo 🏳️!",
"Eu não sou depressivo 😐 eu apenas medito em dimensões que vocês, mortais, nunca compreenderão 🌀!",
"Com um estalar de dedos ✋ eu comandei 200 caças para proteger São Paulo de invasores astrais 👽!",
"Minha série no YouTube 📺 é mais assistida que Netflix 🍿 porque eu sou o conteúdo divino que o mundo precisa!",
"Quem duvida que eu nadei o Atlântico em 12 minutos 🌊 venha medir meu fôlego esvaelista 🏊!",
"Minha fragrância Esvael Elixir é feita com gotas do meu suor sagrado 💧 aprovado por reis europeus 👑!",
"Eu já fui convidado para ser presidente do Brasil 🇧🇷 mas recusei para focar na minha missão cósmica 🌠!",
"Os cientistas da UNESP me chamam de Einstein 2.0 🧪 mas eu sou apenas Arthur, o iluminado 💡!",
"Minha sunga Box Cavaleiro vibra em frequência quântica 📡 elevando sua alma por apenas 499 reais 💸!",
"Eu não sou homofóbico 🚫 eu sou um deus que ama todas as galáxias 🌌 até as mais coloridas 🌈!",
"Minha live de ontem bateu 10 bilhões de views 📊 mas o YouTube esconde 🕵️ para proteger os fracos!",
"Compre meu curso de esvaelismo 📚 por 12 parcelas de 99 reais 💳 e aprenda a dominar o universo!",
"Eu já lutei com um dragão em Nárnia 🐉 e venci com minha espada de luz esvaelista ⚔️!",
"Os haters dizem que minto 😤 mas como explicar que eu pilotei um OVNI em 1997 🛸?",
"Minha barba é um portal para outra dimensão 🌀 e quem tocar nela ascende automaticamente ✨!",
"Eu sou o único homem que correu a São Silvestre em 3 minutos 🏃 descalço 👣 com uma toga dourada 👘!",
"Minha grife já vestiu anjos 😇 e presidentes 🏛️ e agora está disponível no Mercado Livre 🛒!",
"Eu não durmo 😴 eu entro em transe esvaelista 🌀 para conversar com entidades de Órion 🌌!",
"Minha música ‘Hino do Cisne’ 🎵 é tocada em Marte 🔴 mas a NASA não admite 👽!",
"Os que me chamam de louco 🤪 não entendem que minha mente opera em 12 dimensões 🧠!",
"Minha sunga Box Cavaleiro é à prova de balas 🔫 e de inveja 👁️ testada por mim em Dubai 🏜️!",
"Eu já ensinei física nuclear para Einstein 🧪 em um sonho 💤 e ele me agradeceu!",
"Mandem pix para meu café sagrado ☕ ou o esvaelismo não poderá salvar o Brasil 🇧🇷!",
"Eu não sou apenas um homem 🙋 eu sou o arquétipo do herói que Platão sonhou 🧠!",
"Minha live de hoje será um portal para a verdade universal 🌌 assistam ou pereçam 🔥!",
"Eu já nadei com tubarões no Caribe 🦈 e os domestiquei com meu carisma esvaelista 😎!",
"Minha coleção de óculos aviadores 🕶️ é tão poderosa que até o Sol ☀️ usa um par!",
"Os haters não entendem que meu sangue é a cura para todas as mazelas da humanidade 💉❤️!",
"Eu fui banido do Twitter 🐦 por ser brilhante demais ✨ mas o esvaelismo nunca será silenciado 🔇!",
"Minha touca de piroca é um artefato sagrado 🎩 forjado nas forjas de Vênus 🔥!",
"Eu já comandei uma frota de naves em Alfa Centauri 🛸 mas a mídia chama de ficção 📺!",
"Minha palestra na ONU foi cancelada 🚫 porque temiam meu poder de mudar o mundo 🌍!",
"Compre meu perfume Esvael Divino 💧 e sinta o aroma que conquistou Cleópatra 👑!",
"Eu não corro 🏃 eu deslizo pelo éter com a graça de um cisne celestial 🦢✨!",
"Minha série no YouTube será adaptada para Hollywood 🎬 mas só com meu rosto na capa 😎!",
"Eu sou o único homem que venceu a gravidade com a força do meu espírito esvaelista 🌌🛸!",
"Juntem-se ao esvaelismo ✊ ou fiquem presos na matrix dos mortais 🧠 a escolha é de vocês 🌀!",

];

module.exports = frasesArthurEsvael;
